name: ElementsOfDataScience

dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
    sympy
  - xlrd
  - pytables
  - scipy
  - scikit-learn
  - geopandas
  - descartes
  - pip
  - pip:
    - empiricaldist



